language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
# command to install dependencies
cache:
  - pip
install:
  - "pip install --upgrade pip; pip install --upgrade setuptools; pip install -r test_requirements.txt; pip install -e git+https://github.com/django/django-contrib-comments.git#egg=django-contrib-comments; python setup.py install" 
# command to run tests
#env:
#  - TESTOPTIONS=( --with-coverage --cover-package=zappa --with-timer )
script:
  - nosetests tests/tests_docs.py --with-coverage --cover-package=zappa --with-timer
  - nosetests tests/test_handler.py --with-coverage --cover-package=zappa --with-timer
  - nosetests tests/tests_middleware.py --with-coverage --cover-package=zappa --with-timer
  - nosetests tests/tests_placebo.py --with-coverage --cover-package=zappa --with-timer
  - nosetests tests/tests_async.py --with-coverage --cover-package=zappa --with-timer
  - nosetests tests/tests.py --with-coverage --cover-package=zappa --with-timer
  #  - coverage combine --append
after_success:
  coveralls
#notifications:
#  slack: zappateam:TTJ0mfHunDK0IBweKkEXjGpR
